# Generated by Django 4.1.7 on 2023-04-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Firstname", models.CharField(max_length=100)),
                ("Lastname", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("Address", models.CharField(max_length=500)),
                ("Message", models.TextField()),
            ],
        ),
    ]
